### PR TITLE
[CHAOS-155] Return ID of new org when it is created

### PR DESCRIPTION
**Pull request by XenocidePC**
<o/

### CODE REVIEW

**Review by evan-a-w — CHANGES_REQUESTED** [review]
This is truly a brilliant piece of code... wow... But I don't think it will work with the frontend because the frontent just used the response directly as an org ID (ie. not .id as it would be here) - have you tested?

**Comment by XenocidePC** [comment]
What is testing

**Comment by evan-a-w** [comment]
> 

This is fair. btw, Json<usize> does work  ! !  !! !

**Comment by XenocidePC** [comment]
Frontend should change because campaign does same return structure (also cannot return just i32 because rocket angry)

**Comment by evan-a-w** [comment]
> Frontend should change because campaign does same return structure (also cannot return just i32 because rocket angry)

Fair, mr someone else can do then - i make tik

**Comment by XenocidePC** [comment]
@evan-a-w i fix frontend i think

**Review by zaxutic — APPROVED** [review]
looks good 😎

**Pull request merged**
