### PR TITLE
fix(application_page): fix infinite render loop

### PR DESCRIPTION
**Pull request by Varun-Sethu**
While consulting with Michael about an issue he was having I managed to track down the source of the infinite loop :).

### CODE REVIEW

**Comment by Varun-Sethu** [comment]
Extremely epic PR btw 😎

**Review by zaxutic — APPROVED** [review]
very poggers 😎 smh @evan-a-w

**Comment by imagine-hussain** [comment]
can we name and shame @evan-a-w publically

**Comment by Varun-Sethu** [comment]
> can we name and shame @evan-a-w publically

and @stapletm for review it smh

**Pull request merged**
